/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Availability = "in_stock" | "out_of_stock" | "unknown";

export type ExtractMethod = "json-ld" | "meta" | "microdata" | "selector";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ComparisonGroupItems {
  group_id: string;
  item_id: string;
  position: number;
}

export interface ComparisonGroups {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
}

export interface Items {
  archived_at: Timestamp | null;
  consecutive_failures: Generated<number>;
  created_at: Generated<Timestamp>;
  currency: string | null;
  extract_failing: Generated<boolean>;
  extract_method: ExtractMethod | null;
  folder: Generated<string>;
  id: Generated<string>;
  image: string | null;
  last_alert_price: number | null;
  last_alerted_at: Timestamp | null;
  last_checked_at: Timestamp | null;
  next_check_at: Generated<Timestamp>;
  notes: string | null;
  price_selector: string | null;
  price_selector_failing: Generated<boolean>;
  store_hostname: string;
  target_price: number | null;
  title: string | null;
  url: string;
}

export interface PriceChecks {
  availability: Generated<Availability>;
  checked_at: Generated<Timestamp>;
  id: Generated<Int8>;
  item_id: string;
  price: number;
}

export interface DB {
  comparison_group_items: ComparisonGroupItems;
  comparison_groups: ComparisonGroups;
  items: Items;
  price_checks: PriceChecks;
}
